#!/bin/bash
#SBATCH --job-name=single_file
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-node=4
#SBATCH --ntasks-per-socket=2
#SBATCH --mem-per-cpu=15000mb
#SBATCH --distribution=cyclic:cyclic
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ahmed.waseem@ufl.edu
#SBATCH --time=00:05:00
date;hostname;pwd
module load mamba 
mamba activate bvl
python -u -m memory_profiler faiss_implement.py >> output.out 2>&1